# Generated by Django 5.2.1 on 2025-05-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageclassification',
            name='user',
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='predicted_label',
            field=models.CharField(max_length=100),
        ),
    ]
